// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB58JtI_QhHfiIkyAeXDlbWBcciMPVruNk',
    appId: '1:912733716262:web:1be4779f600e7a590ccbe7',
    messagingSenderId: '912733716262',
    projectId: 'do-an-cnpm-1',
    authDomain: 'do-an-cnpm-1.firebaseapp.com',
    storageBucket: 'do-an-cnpm-1.firebasestorage.app',
    measurementId: 'G-XVD1R38XT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChl9FP-f0iB9S0--yvdUjuvb-41tavl4E',
    appId: '1:912733716262:android:685ec2709325a4af0ccbe7',
    messagingSenderId: '912733716262',
    projectId: 'do-an-cnpm-1',
    storageBucket: 'do-an-cnpm-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA74gVcoxkD3nDovAdWdoFUbW2PwJLM1H0',
    appId: '1:912733716262:ios:73b74975062a20540ccbe7',
    messagingSenderId: '912733716262',
    projectId: 'do-an-cnpm-1',
    storageBucket: 'do-an-cnpm-1.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA74gVcoxkD3nDovAdWdoFUbW2PwJLM1H0',
    appId: '1:912733716262:ios:73b74975062a20540ccbe7',
    messagingSenderId: '912733716262',
    projectId: 'do-an-cnpm-1',
    storageBucket: 'do-an-cnpm-1.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB58JtI_QhHfiIkyAeXDlbWBcciMPVruNk',
    appId: '1:912733716262:web:8d0058a0b9f5bab10ccbe7',
    messagingSenderId: '912733716262',
    projectId: 'do-an-cnpm-1',
    authDomain: 'do-an-cnpm-1.firebaseapp.com',
    storageBucket: 'do-an-cnpm-1.firebasestorage.app',
    measurementId: 'G-3SNMP96K66',
  );
}
